#spring:
#  datasource:
#    #generate-unique-name: false #bu ifade h2 veri tabaninin jdbc url kisminin her seferinde degismemesi icin
#    #embeded database'lerde verinin kaybolmamasi icin yukaridaki kodu yorum yapip asagidaki konfigurasyonu yapiyoruz
#    #oncelikle verinin dosyada tutulmasi icin bir path tanimlayacagiz
#    #h2'den sonraki . bulundugumuz adresi isaret eder
#    url: jdbc:h2:./devdb #devdb isimli dosyada bilgiler tutulacak
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update #uygulama baslarken uygulama entity'leri ile mevcut veri tabanini kıyasla ve degisiklikleri uygula
#    
#kullaniciAdi parametresini biz veri tabani oncesinde validation kontrolune tabi tutuyoruz..
#..ancak bu islem ekstra olarak veri tabani isleminde de hibernate tarafindan uygulaniyor. Bu katmanda uygulanmasin..
#..diye asagidaki konfigurasyonu yapiyoruz
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

#veri tabanindan verileri pageable ozelligi kullanarak cekerken page ve size ozelliklerinin degerlerini degistirebiliriz
  data:
    web:
      pageable:
        page-parameter: pageNumber
        size-parameter: pageSize
        
#hangi profilin aktif edilecegini secelim  
#birden fazla profil aktif edildiginde en son olusturulan (profil listesine en son eklenen DEGIL) profil baz alinir      
  profiles:
    active:
    - dev    
    
# multipart file save ederken default max degeri (1MB) degistirelim
  servlet:
    multipart:
      max-file-size: 10MB
        
#kullanici profil fotolarini kaydedecegimiz dosya yolunu belirtelim. Spring tarafinda demistik ki; bu degeri..
#..'upload-path'den al
hoaxify:
  upload-path: picture-storage

# *** bu configuration dosyasinda farkli profiller olusturabiliriz ***
# Profilleri birbirinden ayirmak icin '---' kullanilir
---
spring:
  config:
    activate:
      on-profile: production
hoaxify:
  upload-path: storage-production
---
spring:
  config:
    activate:
      on-profile: dev
hoaxify:
  upload-path: storage-dev






